name: tests

on:
  merge_group:
  push:
    branches-ignore:
    # temporary GH branches relating to merge queues (jaraco/skeleton#93)
    - gh-readonly-queue/**
    tags:
    # required if branches-ignore is supplied (jaraco/skeleton#103)
    - '**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  # Environment variable to support color support (jaraco/skeleton#66)
  FORCE_COLOR: 1

  # Suppress noisy pip warnings
  PIP_DISABLE_PIP_VERSION_CHECK: 'true'
  PIP_NO_PYTHON_VERSION_WARNING: 'true'
  PIP_NO_WARN_SCRIPT_LOCATION: 'true'

  # Ensure tests can sense settings about the environment
  TOX_OVERRIDE: >-
    testenv.pass_env+=GITHUB_*,FORCE_COLOR


jobs:
  test:
    strategy:
      # https://blog.jaraco.com/efficient-use-of-ci-resources/
      fail-fast: false 
      matrix:
        python:
        - "3.9"
        - "3.10"
        - "3.13"
        - "3.8"
    
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        - macos-13
        include:
        - python: "3.10"
          platform: ubuntu-latest
        - python: "3.11"
          platform: ubuntu-latest
        - python: "3.12"
          platform: ubuntu-latest
        - python: "3.14"
          platform: ubuntu-latest
        - platform: ubuntu-latest
          python: "3.10"
          distutils: stdlib
         
        # TODO: Re-evaluate the need for the following workaround
        # exclude:
        # - {python: "3.9", platform: "macos-latest"}  # actions/setup-python#981
    runs-on: ${{ matrix.platform }}
    continue-on-error: ${{ matrix.python == '3.14' }}
    env:
      SETUPTOOLS_USE_DISTUTILS: ${{ matrix.distutils || 'local' }}
    timeout-minutes: 75
    steps:
      - uses: actions/checkout@v4
      # - name: Install Pip
      #   run: python3 -m ensurepip
      - name: Print Setuptools Version
        run: python -m pip show setuptools
      - name: Setup Python
        id: python-install
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
